from agent.llm_client import LLMClient


class TestbenchGenerator:

    def __init__(self):
        self.llm = LLMClient()

    def generate(
        self,
        rtl_info,
        verification_plan,
        adaptation=None,
        reference_behavior=None,
        strategies=None,
        test_cases=None
    ):

        strategies = strategies if strategies else []
        test_cases = test_cases if test_cases else []

        strategy_names = [
            strategy.value if hasattr(strategy, "value") else str(strategy)
            for strategy in strategies
        ]

        prompt = f"""
You are an expert Verilog verification engineer.

Your task is to generate ONLY a testbench for an EXISTING RTL module.

The RTL module already exists.

You must NOT recreate, redefine, or copy the RTL module.

The testbench must instantiate the existing DUT.

================ RTL INFORMATION ================

Module:
{rtl_info["module"]}

Inputs:
{rtl_info["inputs"]}

Outputs:
{rtl_info["outputs"]}

Assignments:
{rtl_info["assignments"]}

================ VERIFICATION PLAN ================

{verification_plan}

================ REFERENCE MODEL ================

{reference_behavior if reference_behavior else "No reference model provided."}

The reference model represents the intended functional behavior.

Use the reference model to determine EXPECTED outputs.

IMPORTANT:

The RTL implementation is NOT the source of truth.

The reference model is the source of truth for expected behavior.

Never modify the expected behavior to match the RTL.

================ SELECTED TEST STRATEGIES ================

{strategy_names}

The selected strategies determine how the DUT must be tested.

Use all selected strategies when generating the testbench.

================ GENERATED TEST CASES ================

{test_cases}

These test cases were generated by the verification strategy engine.

Use them as input vectors for the testbench.

Do not remove valid test cases.

Do not change the intended expected behavior.

================ PREVIOUS ADAPTATION ================

{adaptation if adaptation else "No previous failure. This is the first verification attempt."}

================ CRITICAL VERIFICATION RULES ================

The testbench must independently determine the EXPECTED behavior
of the DUT.

NEVER derive the expected value by copying the RTL implementation.

For example, if the RTL contains:

assign sum = a + b + 1;

and the intended behavior is addition:

expected_sum = a + b;

NOT:

expected_sum = a + b + 1;

The testbench must detect implementation bugs.

The expected-value calculation must represent the INTENDED
functional behavior, not the CURRENT RTL implementation.

The testbench must contain real functional comparisons.

Do not create a testbench that merely checks whether the
DUT produces some value.

Each test case must compare:

EXPECTED VALUE
against
ACTUAL DUT OUTPUT

and report PASS or FAIL accordingly.

================ TESTING REQUIREMENTS ================

1. Generate Verilog-2001 only.
2. Generate ONLY the testbench.
3. Do NOT generate the RTL module.
4. Do NOT declare a module named "{rtl_info["module"]}".
5. The existing DUT module is named "{rtl_info["module"]}".
6. Create exactly ONE testbench module.
7. The testbench module name must be "{rtl_info["module"]}_tb".
8. Instantiate the existing DUT.
9. Declare appropriate reg inputs.
10. Declare appropriate wire outputs.
11. Use the supplied test cases.
12. Cover every selected verification strategy.
13. Include boundary cases when BOUNDARY is selected.
14. Include representative normal cases when NORMAL is selected.
15. Include every generated combination when EXHAUSTIVE is selected.
16. Calculate expected outputs independently.
17. Compare expected outputs with actual DUT outputs.
18. Increment a failure counter whenever a mismatch occurs.
19. Increment a passed-test counter for successful comparisons.
20. Print clear PASS and FAIL messages.
21. Print a final verification summary.
22. Print total tests executed.
23. Print total tests passed.
24. Print total tests failed.
25. Call $finish.
26. The testbench must compile with Icarus Verilog.
27. If a previous adaptation recommendation is provided,
    incorporate relevant recommendations.
28. Do not blindly trust the RTL implementation.
29. Do not use the RTL assignment itself as the expected-value model.
30. The testbench must be capable of detecting an incorrect
    constant, incorrect operator, missing operation, or similar
    functional defect.
31. Do not generate self-fulfilling tests.
32. The expected model must be independent from the DUT.
33. Do not include another copy of the DUT.
34. Do not include markdown.
35. Do not include ```verilog.
36. Return ONLY the Verilog testbench source code.

================ FINAL VALIDATION REQUIREMENT ================

Before returning the testbench, mentally verify:

"If the RTL contains a deliberate +1 bug in an otherwise
normal addition module, will this testbench detect it?"

If the answer is NO, revise the testbench.

Return ONLY Verilog code.
"""

        generated_testbench = self.llm.generate(prompt)

        # Clean common formatting issues from LLM output.
        generated_testbench = generated_testbench.strip()

        if generated_testbench.startswith("```"):
            lines = generated_testbench.splitlines()

            if lines and lines[0].strip().startswith("```"):
                lines = lines[1:]

            if lines and lines[-1].strip() == "```":
                lines = lines[:-1]

            generated_testbench = "\n".join(lines).strip()

        # Gemini may occasionally remove the backtick from
        # the Verilog `timescale directive.
        if generated_testbench.startswith("timescale "):
            generated_testbench = "`" + generated_testbench

        return generated_testbench